# Generated by Django 5.1.3 on 2025-05-12 06:27

import pgcrypto.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recentlyvieweditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(blank=True, max_length=32, null=True),
        ),
    ]
