# Generated by Django 5.0.13 on 2025-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_original_uah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
