# Generated by Django 5.1.3 on 2025-04-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_category_item_description_eng_item_description_rus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description_eng',
            new_name='description_p1_eng',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description_rus',
            new_name='description_p1_rus',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description_ua',
            new_name='description_p1_ua',
        ),
        migrations.AddField(
            model_name='item',
            name='description_p2_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_p2_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_p2_ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
