# Generated by Django 5.1.3 on 2025-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_description_eng_item_description_p1_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
