# Generated by Django 5.1.3 on 2025-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video_poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
