# Generated by Django 5.1.3 on 2025-04-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_video_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_ua', models.CharField(max_length=255)),
                ('key_eng', models.CharField(max_length=255)),
                ('key_rus', models.CharField(max_length=255)),
                ('value_ua', models.CharField(max_length=255)),
                ('value_eng', models.CharField(max_length=255)),
                ('value_rus', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='items.item')),
            ],
        ),
    ]
