# Generated by Django 5.1.3 on 2025-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_itemcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='feature_1_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_1_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_1_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_2_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_2_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_2_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_3_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_3_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_3_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_4_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_4_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_4_ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
