# Generated by Django 5.1.3 on 2025-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_feature_1_eng_item_feature_1_rus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='feature_1_header_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_1_header_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_1_header_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_2_header_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_2_header_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_2_header_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_3_header_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_3_header_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_3_header_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_4_header_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_4_header_rus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='feature_4_header_ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
