# Generated by Django 5.1.3 on 2025-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
