# Generated by Django 5.1.3 on 2025-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_old_price_uah'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='item_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='item_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='item_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
