# Generated by Django 5.1.3 on 2025-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_item_height_item_item_length_item_item_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
