# Generated by Django 5.0.13 on 2025-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_assigned_to_order_order_special_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oblast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
