# Generated by Django 5.0.13 on 2025-03-31 13:48

import pgcrypto.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_oblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(max_length=255),
        ),
    ]
