# Generated by Django 5.0.13 on 2025-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_notes_order_patronymic_alter_order_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='notes',
            new_name='customer_notes',
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
