# Generated by Django 5.0.13 on 2025-04-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_price_uah',
        ),
    ]
