# Generated by Django 5.0.13 on 2025-04-01 08:57

import pgcrypto.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_total_price_order_total_price_uah'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOrdersEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', pgcrypto.fields.TextPGPSymmetricKeyField(max_length=255)),
            ],
        ),
    ]
