# Generated by Django 5.0.13 on 2025-04-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_notificationordersemails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationOrdersEmails',
        ),
    ]
